export interface SmartAnalysisValues {
  spermId: string;
  idLocation: string;
  indication: string;
  semenType: 'Fresh' | 'Frozen';
  abstinence: string;
  date: string;
  collProblem: string;
  labOperator: string;
  validTill: string;
  contamination: string;
  method: string;
  appearance: string;
  colour: string;
  viscosity: string;
  normomorphs1: string;
  normomorphs2: string;
  liquefaction: string;
  timeOfLiq: string;
  agglutination: string;
  antibodies: string;
  fructose: string;
  linearity: string;
  velocity: string;
  ph: string;
  beforeVol: string;
  beforeSperms: string;
  beforeMotility: string;
  beforeProgMotility: string;
  beforeGrade1: string;
  beforeGrade2: string;
  beforeGrade3: string;
  beforeGrade4: string;
  beforeWbc: string;
  beforeRbc: string;
  beforeEpith: string;
  beforeRound: string;
  recovery: string;
  hams: boolean;
  afterVol: string;
  afterSperms: string;
  afterMotility: string;
  afterProgMotility: string;
  afterLinearity: string;
  survival24: string;
  survival48: string;
  afterGrade1: string;
  afterGrade2: string;
  afterGrade3: string;
  afterGrade4: string;
  afterWbc: string;
  afterRbc: string;
  afterEpith: string;
  afterRound: string;
}

export function emptySmartAnalysis(): SmartAnalysisValues {
  return {
    spermId: '',
    idLocation: '',
    indication: '',
    semenType: 'Fresh',
    abstinence: '0',
    date: '',
    collProblem: '',
    labOperator: '',
    validTill: '',
    contamination: '',
    method: '',
    appearance: '',
    colour: '',
    viscosity: '',
    normomorphs1: '0',
    normomorphs2: '0',
    liquefaction: '',
    timeOfLiq: '',
    agglutination: '',
    antibodies: '',
    fructose: '',
    linearity: '',
    velocity: '0',
    ph: '',
    beforeVol: '0',
    beforeSperms: '0',
    beforeMotility: '0',
    beforeProgMotility: '0',
    beforeGrade1: '',
    beforeGrade2: '',
    beforeGrade3: '',
    beforeGrade4: '',
    beforeWbc: '0',
    beforeRbc: '0',
    beforeEpith: '0',
    beforeRound: '0',
    recovery: '',
    hams: false,
    afterVol: '0',
    afterSperms: '0',
    afterMotility: '0',
    afterProgMotility: '0',
    afterLinearity: '',
    survival24: '0',
    survival48: '0',
    afterGrade1: '',
    afterGrade2: '',
    afterGrade3: '',
    afterGrade4: '',
    afterWbc: '0',
    afterRbc: '0',
    afterEpith: '0',
    afterRound: '0',
  };
}

export const SMART_MASTER_CATS = {
  labOperator: 2,
  method: 3,
  appearance: 4,
  colour: 5,
  viscosity: 6,
  liquefaction: 7,
  fructose: 8,
  spermId: 22,
  collProblem: 24,
  linearity: 25,
  contamination: 27,
} as const;
